trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Cache@2
  displayName: 'Cache vcpkgs artifacts'
  inputs:
    key: $(Build.SourcesDirectory)/build_msvc/vcpkg-packages.txt | "$(Agent.OS)"
    path: '$(VCPKG_INSTALL_PATH)'

- task: run-vcpkg@0
  displayName: 'Run vcpkg'
  inputs:
    # Response file stored in source control, it provides the list of ports and triplet(s).
    vcpkgArguments: --triplet x64-windows-static @$(Build.SourcesDirectory)/build_msvc/vcpkg-packages.txt
    # Location of the vcpkg as submodule of the repository.
    vcpkgDirectory: $(VCPKG_DIRECTORY)
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $env:PACKAGES = Get-Content -Path build_msvc\vcpkg-packages.txt
            Write-Host "vcpkg list: $env:PACKAGES"
            if(!(Test-Path -Path ($(VCPKG_INSTALL_PATH)))) {
                cd c:\tools
                dir
                git clone https://github.com/microsoft/vcpkg.git
                cd vcpkg
                $env:GIT_REDIRECT_STDERR = '2>&1' # git is writing non-errors to STDERR when doing git pull. Send to STDOUT instead.
                git pull origin master
                .\bootstrap-vcpkg.bat
                Add-Content "C:\tools\vcpkg\triplets\x64-windows-static.cmake" "set(VCPKG_BUILD_TYPE release)"
                .\vcpkg install --triplet x64-windows-static $env:PACKAGES.split()
            }
            else {
              Write-Host "required vcpkg packages already installed."
            }
            c:\tools\vcpkg\vcpkg integrate install

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'build_msvc\msvc-autogen.py'

- task: VSBuild@1
  inputs:
    solution: 'build_msvc\Bitcoin.sln'
    vsVersion: '16.0'
    platform: 'x64'
    configuration: 'Release'
    maximumCpuCount: true
    msbuildArchitecture: 'x64'
