name: CI

on:
  push:
    branches:    
      - actions_test

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Sanity Test
      run: echo Bitcoin Core build starting...
    - name: Update vcpkg and install packages
      env:
        VCPKG_INSTALL_PATH: "$env:VCPKG_INSTALLATION_ROOT/installed"
        PLATFORM: x64
      run: |
        $env:PACKAGES = Get-Content -Path "$env:GITHUB_WORKSPACE/build_msvc/vcpkg-packages.txt
        Write-Host "vcpkg list: $env:PACKAGES"
    - name: Generate project files
      run: python build_msvc\msvc-autogen.py
    - name: Build
      run: msbuild build_msvc\bitcoin.sln /m /v:n
      
