name: CI

on:
  push:
    branches:    
      - actions_test

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Sanity Test
      run: echo Bitcoin Core build starting...
    - name: Update vcpkg and install packages
      env:
        VCPKG_INSTALL_PATH: "$env:VCPKG_INSTALLATION_ROOT/installed"
        PLATFORM: x64
      run: |
        $env:PACKAGES = Get-Content -Path "$env:GITHUB_WORKSPACE/build_msvc/vcpkg-packages.txt
        Write-Host "vcpkg list: $env:PACKAGES"
        if(!(Test-Path -Path ("$env:VCPKG_INSTALL_PATH))) {
          cd $env:VCPKG_INSTALLATION_ROOT
          #$env:GIT_REDIRECT_STDERR = '2>&1' # git is writing non-errors to STDERR when doing git pull. Send to STDOUT instead.
          git pull origin master
          .\bootstrap-vcpkg.bat
          #Add-Content "C:\tools\vcpkg\triplets\$env:PLATFORM-windows-static.cmake" "set(VCPKG_BUILD_TYPE release)"
          #.\vcpkg install --triplet $env:PLATFORM-windows-static $env:PACKAGES.split() > $null
          .\vcpkg install --triplet $env:PLATFORM-windows-static $env:PACKAGES.split()
          #cd "$env:APPVEYOR_BUILD_FOLDER"
          cd $env:GITHUB_WORKSPACE
        }
        else {
          Write-Host "required vcpkg packages already installed."
        }
    - name: Generate project files
      run: python build_msvc\msvc-autogen.py
    - name: Build
      run: msbuild build_msvc\bitcoin.sln /m /v:n
      
